spring.application.name=auth-service
# Spring will look for an environment variable named JWT_SECRET first.
# If it's running locally outside Docker, it will use the fallback value after the colon.
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Database Connection (with local fallbacks for testing)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexus_auth}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:hello123}

# Tells Spring/Hibernate to automatically create our 'user_credentials' table
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Change from localhost to discovery-server
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:password@localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
# Set the port for this specific microservice so it doesn't clash with others
server.port=8082