services:
  postgres:
    image: postgres:17-alpine
    container_name: nexus-postgres
    # ports:
    #   - "5433:5432" # Uncomment if you need to use pgAdmin locally
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME} # Creates nexus_auth automatically
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/ # Runs the script for product_db

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - discovery-server

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${PRODUCT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
      - discovery-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - DB_URL=jdbc:postgresql://postgres:5432/${AUTH_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - discovery-server

volumes:
  postgres_data: