spring.application.name=product-service

# Use placeholders for environment-specific values
# Change 'localhost' to 'nexus-postgres'
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hello123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Use placeholder for Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:password@localhost:8761/eureka/}

# Keep your JPA and Hikari settings as they are
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable Virtual Threads (Java 25)
spring.threads.virtual.enabled=true
# The maximum number of connections Hikari will keep open.
# Formula: (core_count * 2) + effective_spindle_count is a good production starting point.
spring.datasource.hikari.maximum-pool-size=20

# How long a user request will wait for a free DB connection before throwing an error (in milliseconds).
# Prevents requests from hanging forever.
spring.datasource.hikari.connection-timeout=30000

# The maximum amount of time a connection can sit completely idle in the pool.
spring.datasource.hikari.idle-timeout=600000

# The maximum lifetime of a connection in the pool.
spring.datasource.hikari.max-lifetime=1800000
eureka.instance.prefer-ip-address=true