spring.application.name=inventory-service
server.port=8084

# Database settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hello123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:password@localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
